### ISSUE TITLE
Split GQL operations file

### ISSUE THREAD

**Issue by joshxg** [openmsupply/openmsupply-client#631]
The GQL Operations file is a bit too big and annoying to work with.

You can generate using a glob pattern `**/*.graphql` which means we could have a .. `queries`? `operations`? file next to the `api` file in each of the sub packages?

**Comment by joshxg** [comment]
Had a quick look..

`yarn add  @graphql-codegen/near-operation-file-preset -W -D` at the top level 

and a config like:

```
overwrite: true
schema: ["https://demo-open.msupply.org:8000/graphql", "./packages/common/src/additions.schema.graphql"]
documents: './packages/common/src/operations.graphql'
documents: 
  - 'packages/**/*.graphql'
generates:
  ./packages/common/src/types/schema.ts:
    plugins:
@ -11,4 +12,15 @@ generates:
    config:
      scalars:
        DateTime: string
        NaiveDate: string
        NaiveDate: string
  packages/:
    documents: 
      - 'packages/**/*.graphql'
      - '!packages/common/src/additions.schema.graphql'
    preset: near-operation-file
    presetConfig:
      extension: .generated.ts
      baseTypesPath: ./common/src/types/schema.ts
    plugins:
      - typescript-operations
      - typescript-graphql-request
```

with a `operations.graphql` file next to the `api` file will generate a `operations.generated.tsx` file.

Since we're currently using a single api object, we'd have to do something like

```
export const useOutboundShipmentDetailApi = (): ReturnType<typeof getSdk> => {
  const { client } = useOmSupplyApi();
  return getSdk(client);
};
```
to use the same client which has auth and url details.


it'll take a bit of time so I'm dropping this here for now to come back to it
